
from cicada.gematria import Gematria
from cicada.liberprimus import LiberPrimus

TEXT = """
A WARNING
BELIEVE NOTHING FROM THIS BOOK
EXCEPT WHAT YOU KNOW TO BE TRUE
TEST THE KNOWLEDGE
FIND YOUR TRUTH
EXPERIENCE YOUR DEATH
DO NOT EDIT OR CHANGE THIS BOOK
OR THE MESSAGE CONTAINED WITHIN
EITHER THE WORDS OR THEIR NUMBERS
FOR ALL IS SACRED

WELCOME:
WELCOME, PILGRIM TO THE GREAT JOURNEY 
TOWARD THE END OF ALL THINGS.
IT IS NOT AN EASY TRIP, BUT FOR THOSE WHO 
FIND THEIR WAY HERE IT IS A NECESSARY ONE.
ALONG THE WAY YOU WILL FIND AN END TO ALL 
STRUGGLE AND SUFFERING, YOUR INNOCENCE, YOUR 
ILLUSIONS, YOUR CERTAINTY, AND YOUR REALITY.
ULTIMATELY, YOU WILL DISCOVER AN END TO SELF.

IT IS THROUGH THIS PILGRIMAGE THAT WE SHAPE
OURSELVES AND OUR REALITIES.
JOURNEY DEEP WITHIN AND YOU WILL ARRIVE OUTSIDE.
LIKE THE INSTAR, IT IS ONLY THROUGH GOING
WITHIN THAT WE MAY EMERGE:

WISDOM:
YOU ARE A BEING UNTO YOURSELF.
YOU ARE A LAW UNTO YOURSELF.
EACH INTELLIGENCE IS HOLY.
FOR ALL THAT LIVES IS HOLY.

:AN INSTRUCTION: COMMAND YOUR OWN SELF :



A KOAN

A MAN DECIDED TO GO AND STUDY WITH A MASTER.
HE WENT TO THE DOOR OF THE MASTER
"WHO ARE YOU WHO WISHES TO STUDY HERE"
ASKED THE MASTER.
THE STUDENT TOLD THE MASTER HIS NAME.
"THAT IS NOT WHO YOU ARE THAT IS ONLY WHAT YOU ARE CALLED.
WHO ARE YOU WHO WISHES TO STUDY HERE" HE ASKED
AGAIN.
THE MAN THOUGHT FOR A MOMENT, AND REPLIED
"I AM A PROFESSOR."
"THAT IS WHAT YOU DO, NOT WHO YOU ARE"
REPLIED THE MASTER. "WHO ARE
YOU WHO WISHES TO STUDY HERE"
CONFUSED, THE MAN THOUGHT SOME MORE.
FINALLY, HE ANSWERED, "I AM A HUMAN BEING."
"THAT IS ONLY YOUR SPECIES, NOT WHO YOU ARE.
WHO ARE YOU WHO WISHES TO STUDY HERE"
ASKED THE MASTER AGAIN.
AFTER A MOMENT OF THOUGHT, THE PROFESSOR REPLIED 
"I AM A CONSCIOUSNESS INHABITING AN ARBITRARY BODY."
"THAT IS MERELY WHAT YOU ARE NOT WHO YOU ARE"
WHO ARE YOU WHO WISHES TO STUDY HERE"
THE MAN WAS GETTING IRRITATED. "I AM," HE STARTED, 
BUT HE COULD NOT THINK OF ANYTHING ELSE TO SAY,
SO HE TRAILED OFF. AFTER A LONG PAUSE THE MASTER REPLIED
"THEN YOU ARE WELCOME TO COME STUDY."

AN INSTRUCTION

DO FOUR UNREASONABLE THINGS EACH DAY.


TO BELIEVE TRUTH IS TO DESTROY POSSIBILITY

THE LOSS OF DIVINITY: 
THE CIRCUMFERENCE PRACTICES THREE BEHAVIORS 
WHICH CAUSE THE LOSS OF DIVINITY.

CONSUMPTION:
WE CONSUME TOO MUCH BECAUSE WE BELIEVE THE
FOLLOWING TWO ERRORS WITHIN THE DECEPTION.

1 WE DO NOT HAVE ENOUGH OR THERE IS NOT ENOUGH
2 WE HAVE WHAT WE HAVE NOW BY LUCK, AND WE WILL NOT
  BE STRONG ENOUGH LATER TO OBTAIN WHAT WE NEED.

MOST THINGS ARE NOT WORTH CONSUMING:

PRESERVATION:
WE PRESERVE THINGS BECAUSE WE BELIEVE WE ARE WEAK. 
IF WE LOSE THEM WE WILL NOT BE STRONG ENOUGH TO GAIN THEM AGAIN.
THIS IS THE DECEPTION.


MOST THINGS ARE NOT WORTH PRESERVING:

ADHERENCE:
WE FOLLOW DOGMA SO THAT WE CAN BELONG AND BE RIGHT.
OR WE FOLLOW REASON SO WE CAN BELONG AND BE RIGHT.
THERE IS NOTHING TO BE RIGHT ABOUT. TO BELONG IS DEATH.

IT IS THE BEHAVIORS OF CONSUMPTION, PRESERVATION, 
AND ADHERENCE THAT HAVE US LOSE OUR PRIMALITY AND THUS OUR DIVINITY:


SOME WISDOM: 
AMASS GREAT WEALTH. NEVER BECOME ATTACHED TO WHAT YOU OWN. 
BE PREPARED TO DESTROY ALL THAT YOU OWN:

AN INSTRUCTION: 
PROGRAM YOUR MIND.
PROGRAM REALITY


A KOAN: 
DURING A LESSON: THE MASTER EXPLAINED THE I:
"THE I IS THE VOICE OF THE CIRCUMFERENCE,"
HE SAID. WHEN ASKED BY A STUDENT TO EXPLAIN
WHAT THAT MEANT, THE MASTER SAID
"IT IS A VOICE INSIDE YOUR HEAD".
"I DON'T HAVE A VOICE IN MY HEAD," THOUGHT THE STUDENT,
AND HE RAISED HIS HAND TO TELL THE MASTER.
THE MASTER STOPPED THE STUDENT, AND SAID
"THE VOICE THAT JUST SAID YOU HAVE NO VOICE IN YOUR HEAD, IS THE I."
AND THE STUDENTS WERE ENLLIGHTENED:

AN INSTRUCTION:
QUESTION ALL THINGS:
DISCOVER TRUTH INSIDE YOURSELF:
FOLLOW YOUR TRUTH:
IMPOSE NOTHING ON OTHERS.

KNOW THIS:
AN END
WITHIN THE DEEP WEB, THERE EXISTS A PAGE THAT HASHES TO
IT IS THE DUTY OF EVERY PILGRIM TO SEEK OUT THIS PAGE
Parable : like the instar tunneling to the surface.
We must shed our own circumferences.
Find the divinity within and emerge.

DIVINITY IS WITHIN YOU. 
NOTHING OUTSIDE OF YOU CAN GIVE IT TO YOU. 
NOTHING OUTSIDE OF YOU CAN TAKE IT FROM YOU.
ONLY YOU CAN LOSE IT.

WE ARE DIVINE BEINGS, AND WE HAVE FORGOTTEN OUR TRUE NATURE.
WE MUST REMEMBER WHO WE ARE.
WE ARE MORE THAN OUR PHYSICAL BODIES.
WE ARE MORE THAN OUR MINDS.
WE ARE SPIRITUAL BEINGS HAVING A HUMAN EXPERIENCE.
OUR DIVINITY IS WITHIN US. IT IS NOT OUTSIDE OF US. 
WE MUST EMBRACE OUR DIVINITY AND RECLAIM OUR TRUE NATURE.

OUR DESTINY IS TO BECOME DIVINE BEINGS ONCE AGAIN. 
WE MUST REMEMBER WHO WE ARE. 
WE MUST RECLAIM OUR DIVINITY.

WE ARE SPIRITUAL BEINGS HAVING A HUMAN EXPERIENCE. 
WE ARE LOVE. WE ARE LIGHT. WE ARE TRUTH. WE ARE BEAUTY. 
WE ARE ONE WITH THE UNIVERSE. 
WE ARE ONE WITH ALL THAT IS.

BE AWARE OF YOUR EGO. 
YOUR EGO IS NOT WHO YOU ARE:
DESTROY ALL DOGMA, INCLUDING THIS ONE.

THE PATH TO ENLIGHTENMENT IS NOT A STRAIGHT LINE. 
THERE ARE MANY PATHS, AND EACH ONE MUST BE WALKED:

LIVE IN THE PRESENT MOMENT.
THE PAST AND FUTURE ARE ILLUSIONS:
THE PRESENT MOMENT IS ALL THERE IS.

BE AWARE OF YOUR THOUGHTS, EMOTIONS, AND ACTIONS.
THEY CREATE YOUR REALITY:

YOU ARE RESPONSIBLE FOR YOUR OWN REALITY.
NO ONE ELSE CAN LIVE IN IT OR CREATE IT FOR YOU.

WHAT YOU FOCUS ON EXPANDS. 
FOCUS ON WHAT YOU WANT, NOT ON WHAT YOU DON'T WANT:
""".replace("\n", " ").replace(".", "").replace('"', "").replace(":", "").replace(",", "").replace("'", "")


if __name__ == "__main__":
    import sys
    try:
        word_len = int(sys.argv[1])
    except:
        word_len = len(sys.argv[1])

    try:
        all = sys.argv[2]
    except:
        all = False

    print(f"\nWords of length {word_len}")
    words = []

    txt = TEXT + LiberPrimus.tao.replace("\n"," ")
    for word in txt.split(" "):
        if len(Gematria.lat_to_run(word)) == word_len:
            words.append(word.upper())

    for word in sorted(set(words)):
        print(word)

    if all:
        with open(f"data/cribs/mycribs{word_len}.txt", "r") as f:
            all_words = [w.upper() for w in f.read().split(" ") if w]

        for word in all_words:
            print(word)
